# Generated by Django 4.0.2 on 2022-05-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount_bought', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('remaining_amount', models.IntegerField()),
                ('amount_supplied', models.IntegerField()),
                ('imported_from', models.CharField(max_length=100)),
                ('date_of_import', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount_bought', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('remaining_amount', models.IntegerField()),
                ('amount_supplied', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('date_of_delivery', models.DateField()),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.importer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalSupplierLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_due_date', models.DateField()),
                ('license_date_of_issue', models.DateField()),
                ('expiry_date', models.DateField()),
                ('local_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.localsupplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImporterLcence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_due_date', models.DateField()),
                ('license_date_of_issue', models.DateField()),
                ('expiry_date', models.DateField()),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.importer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_bought', models.IntegerField()),
                ('LocalSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.localsupplier')),
            ],
        ),
    ]
