# Generated by Django 4.0.2 on 2022-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_alter_importer_date_of_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='amount_supplied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importer',
            name='remaining_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localsupplier',
            name='amount_supplied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localsupplier',
            name='remaining_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
