# Generated by Django 4.0.2 on 2022-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_alter_importer_amount_supplied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='product_name',
            field=models.CharField(default='product', max_length=100),
        ),
        migrations.AlterField(
            model_name='importer',
            name='amount_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importer',
            name='amount_supplied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importer',
            name='remaining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='localsupplier',
            name='amount_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='localsupplier',
            name='amount_supplied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='localsupplier',
            name='remaining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
