# Generated by Django 4.0.2 on 2022-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_alter_localsupplier_date_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='localsupplier',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
